### ISSUE TITLE
server crashes when a server side demo is recording

### ISSUE THREAD

**Issue by jxsl13** [ZillyInsta/ddnet-insta#61] opened 2023-11-28 07:09 UTC
```
2023-11-27 23:09:16 I assert: sources/ddnet-insta/src/engine/shared/demo.cpp(53): Demo recorder already recording
Illegal instruction
```

Would be cool if we could record stuff for tue tournament.

Seems to be an assertion that is triggered by the `!restart` chat command which crashes the application.

**Comment by ChillerDragon** [comment] 2023-12-01 21:00
Could not reproduce the issue. What I tried is using the ``!restart`` chat command before and after starting a demo with the rcon ``record demo`` command. I also tried ``sv_auto_demo_record 1`` in the server config and then the ``!restart`` chat command or finishing a round by reaching the scorelimit.

The only way I could reach that assert is by running the ``record demo`` rcon command if a demo was already recording. That seems to be a issue in ddnet and will be potentially fixed in the future https://github.com/ddnet/ddnet/issues/7568

If that was the issue you also ran into you can avoid it by not starting a demo twice. If it is another issue I need more information on how to reproduce it.

**Comment by ChillerDragon** [comment] 2023-12-02 11:08
Okay the starting the recording twice manually got fixed in ddnet and is now merged into ddnet-insta. I can no longer reproduce any trigger of said assert. Can you still reproduce? If so I need more details on how to do it :)

**Comment by jxsl13** [comment] 2023-12-02 11:24
the steps to reproduce were:
have the server configured with server side demos enabled (maybe more config settings influence this)
then doba `!restart` as chat command and wait until the countdown hits 0.

**Comment by ChillerDragon** [comment] 2023-12-02 13:07
I started the server like this ``./DDNet-Server "sv_gametype gctf;sv_auto_demo_record 1;sv_auto_demo_max 0;sv_tee_historian 1"`` joined one tee and did ``!restart`` that worked fine. I also connected another tee and tried it again. And also set a ``sv_countdown_round_start 3`` to have the warmup timer followed by the game start countdown and it still worked.

**Comment by jxsl13** [comment] 2023-12-02 15:30
then it's gone.

**Closed** 2023-12-02 19:05 UTC
