### ISSUE TITLE
sv_scorelimit 0 crashes the server

### ISSUE THREAD

**Issue by lukure** [ZillyInsta/ddnet-insta#82] opened 2024-01-06 11:25 UTC

**Comment by lukure** [comment] 2024-01-06 11:27
I'm not sure, is the scorelimit 600 bug for all scorelimits? So is this a general scorelimit bug?

**Comment by ChillerDragon** [comment] 2024-01-13 10:30
Likely a duplicate of https://github.com/ZillyInsta/ddnet-insta/issues/80

**Closed by ChillerDragon** 2024-01-13 10:30 UTC
